### ISSUE TITLE
What is order of execution for $init and $start?

### ISSUE THREAD

**Issue by wzup** [mikolalex/mrr#2]
Which one is called first, `$start` or `$init`?
Because there is concurrency problem with this approach. `nest` is called every time on during init phase. How to avoid it?
I want to set initial state, but I don't want to call `req` for every key in `$init`.
See, you have `page` and `status` in `req` and simultaneously you initialize them in `$init`. So your `req` is called for every key, `page` and `status`.

```
get computed(){
    return {
        $init: {
            page: 1,
            status: 'FOO'
        },
        req: ['nested', this.request.bind(this), 'page', 'clientId', 'sourceId', 'activeTab', 'date', 'status', 'sort'],
}
```

**Comment by mikolalex** [comment]
The variables in "$init" section are initialized, but this is not triggered as a change. E.g.
```js
{
   $init: {
       a: 10,
       b: 20,
   },
   c: [(n, m) => n + m, 'a', 'b']
}
```
in this case "c" won't be calculated! To make it work, you can add another argument.
```js
{
   $init: {
       a: 10,
       b: 20,
   },
   c: [(n, m) => n + m, 'a', 'b', '$start']
}
```
