### ISSUE TITLE
How to find out what property triggered handler?

### ISSUE THREAD

**Issue by wzup** [mikolalex/mrr#3]
Please see initial set up below. 
How can I know which one of 7 properties (`page`, `clientId`, `sourceId`, `tab`, `date`, `status`, `sort`) triggered handler? Is there some special variable inside a handler to check it?

Currently the problem is that the handler is called four times and you cannot know what triggered it.

```
req: ['nested', (cb, page, clientId, sourceId, tab, date, status, sort) => {
        cb('loading', true);

       // How do I know HERE that handler was triggered by `page` and not `clientId`? Like so:
      if(trigger === 'page') { do something }
      else if ( trigger === 'clientId' ) { do something }
    
       fetch('/something').then(res => cb(res))
    }, 'page', 'clientId', 'sourceId', 'activeTab', 'date', 'status', 'sort'],
```

**Comment by mikolalex** [comment]
The simplest way is to turn on logging in console.
`
{ 
   $log: true,
   req: [...]
}
`
Then in console you'll see all the cells' changes in the order they are computed.
If you need some of the arguments not to trigger recalculation, use passive listening, e.g.
`
req: [() => { ... }, '-page', 'clientId', ...]
`
In this case, changes in "page" won't trigger "req" calculation.
